### ISSUE TITLE
one ImportError

### ISSUE THREAD

**Issue by kuazhangxiaoai** [DDGRCF/YOLOX_OBB#10]
/home/yanggang/anaconda3/bin/python3 /home/yanggang/pycharm-community-2021.2/plugins/python-ce/helpers/pydev/pydevd.py --multiproc --qt-support=auto --client 127.0.0.1 --port 37841 --file /home/yanggang/PyCharmWorkspace/YOLOX_OBB/tools/train.py
Connected to pydev debugger (build 212.4746.96)
Traceback (most recent call last):
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 961, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/yanggang/PyCharmWorkspace/YOLOX_OBB/yolox/__init__.py", line 4, in <module>
    from .utils import configure_module
  File "/home/yanggang/anaconda3/lib/python3.8/site-packages/shiboken2/files.dir/shibokensupport/__feature__.py", line 142, in _import
    return original_import(name, *args, **kwargs)
  File "/home/yanggang/PyCharmWorkspace/YOLOX_OBB/yolox/utils/__init__.py", line 6, in <module>
    from .boxes import *
  File "/home/yanggang/anaconda3/lib/python3.8/site-packages/shiboken2/files.dir/shibokensupport/__feature__.py", line 142, in _import
    return original_import(name, *args, **kwargs)
  File "/home/yanggang/PyCharmWorkspace/YOLOX_OBB/yolox/utils/boxes.py", line 9, in <module>
    from .obb import bbox2type
  File "/home/yanggang/anaconda3/lib/python3.8/site-packages/shiboken2/files.dir/shibokensupport/__feature__.py", line 142, in _import
    return original_import(name, *args, **kwargs)
  File "/home/yanggang/PyCharmWorkspace/YOLOX_OBB/yolox/utils/obb/__init__.py", line 1, in <module>
    from .box_iou_rotated import obb_overlaps
  File "/home/yanggang/anaconda3/lib/python3.8/site-packages/shiboken2/files.dir/shibokensupport/__feature__.py", line 142, in _import
    return original_import(name, *args, **kwargs)
  File "/home/yanggang/PyCharmWorkspace/YOLOX_OBB/yolox/utils/obb/box_iou_rotated/__init__.py", line 1, in <module>
    from .box_iou_rotated_wrapper import obb_overlaps
  File "/home/yanggang/anaconda3/lib/python3.8/site-packages/shiboken2/files.dir/shibokensupport/__feature__.py", line 142, in _import
    return original_import(name, *args, **kwargs)
  File "/home/yanggang/PyCharmWorkspace/YOLOX_OBB/yolox/utils/obb/box_iou_rotated/box_iou_rotated_wrapper.py", line 4, in <module>
    from . import box_iou_rotated_ext
ImportError: cannot import name 'box_iou_rotated_ext' from partially initialized module 'yolox.utils.obb.box_iou_rotated' (most likely due to a circular import) (/home/yanggang/PyCharmWorkspace/YOLOX_OBB/yolox/utils/obb/box_iou_rotated/__init__.py)
python-BaseException

Process finished with exit code 130 (interrupted by signal 2: SIGINT)

**Comment by DDGRCF** [comment]
> /home/yanggang/anaconda3/bin/python3 /home/yanggang/pycharm-community-2021.2/plugins/python-ce/helpers/pydev/pydevd.py --multiproc --qt-support=auto --client 127.0.0.1 --port 37841 --file /home/yanggang/PyCharmWorkspace/YOLOX_OBB/tools/train.py Connected to pydev debugger (build 212.4746.96) Traceback (most recent call last): File "", line 991, in _find_and_load File "", line 961, in _find_and_load_unlocked File "", line 219, in _call_with_frames_removed File "/home/yanggang/PyCharmWorkspace/YOLOX_OBB/yolox/**init**.py", line 4, in from .utils import configure_module File "/home/yanggang/anaconda3/lib/python3.8/site-packages/shiboken2/files.dir/shibokensupport/**feature**.py", line 142, in _import return original_import(name, *args, **kwargs) File "/home/yanggang/PyCharmWorkspace/YOLOX_OBB/yolox/utils/**init**.py", line 6, in from .boxes import * File "/home/yanggang/anaconda3/lib/python3.8/site-packages/shiboken2/files.dir/shibokensupport/**feature**.py", line 142, in _import return original_import(name, *args, **kwargs) File "/home/yanggang/PyCharmWorkspace/YOLOX_OBB/yolox/utils/boxes.py", line 9, in from .obb import bbox2type File "/home/yanggang/anaconda3/lib/python3.8/site-packages/shiboken2/files.dir/shibokensupport/**feature**.py", line 142, in _import return original_import(name, *args, **kwargs) File "/home/yanggang/PyCharmWorkspace/YOLOX_OBB/yolox/utils/obb/**init**.py", line 1, in from .box_iou_rotated import obb_overlaps File "/home/yanggang/anaconda3/lib/python3.8/site-packages/shiboken2/files.dir/shibokensupport/**feature**.py", line 142, in _import return original_import(name, *args, **kwargs) File "/home/yanggang/PyCharmWorkspace/YOLOX_OBB/yolox/utils/obb/box_iou_rotated/**init**.py", line 1, in from .box_iou_rotated_wrapper import obb_overlaps File "/home/yanggang/anaconda3/lib/python3.8/site-packages/shiboken2/files.dir/shibokensupport/**feature**.py", line 142, in _import return original_import(name, *args, **kwargs) File "/home/yanggang/PyCharmWorkspace/YOLOX_OBB/yolox/utils/obb/box_iou_rotated/box_iou_rotated_wrapper.py", line 4, in from . import box_iou_rotated_ext ImportError: cannot import name 'box_iou_rotated_ext' from partially initialized module 'yolox.utils.obb.box_iou_rotated' (most likely due to a circular import) (/home/yanggang/PyCharmWorkspace/YOLOX_OBB/yolox/utils/obb/box_iou_rotated/**init**.py) python-BaseException
> 
> Process finished with exit code 130 (interrupted by signal 2: SIGINT)

Are you setup.py successfully
command it is `python setup.py develop`

**Comment by Sidd1609** [comment]
I am also getting the same error
I did setup.py successfully

**Comment by Sidd1609** [comment]
Traceback (most recent call last):
  File "tools/demo.py", line 13, in <module>
    from yolox.exp import get_exp
  File "/content/YOLOX_OBB/tools/yolox/__init__.py", line 4, in <module>
    from .utils import configure_module
  File "/content/YOLOX_OBB/tools/yolox/utils/__init__.py", line 6, in <module>
    from .boxes import *
  File "/content/YOLOX_OBB/tools/yolox/utils/boxes.py", line 9, in <module>
    from yolox.ops.pytorch.nms_rotated import multiclass_obb_nms
  File "/content/YOLOX_OBB/tools/yolox/ops/__init__.py", line 1, in <module>
    from .pytorch import obb_overlaps, multiclass_obb_nms, convex_sort, obb_nms, poly_nms, RoIAlignRotated, RoIAlign
  File "/content/YOLOX_OBB/tools/yolox/ops/pytorch/__init__.py", line 2, in <module>
    from .nms_rotated import *
  File "/content/YOLOX_OBB/tools/yolox/ops/pytorch/nms_rotated/__init__.py", line 1, in <module>
    from .nms_rotated_wrapper import *
  File "/content/YOLOX_OBB/tools/yolox/ops/pytorch/nms_rotated/nms_rotated_wrapper.py", line 4, in <module>
    from . import nms_rotated_ext
ImportError: cannot import name 'nms_rotated_ext' from partially initialized module 'yolox.ops.pytorch.nms_rotated' (most likely due to a circular import) (/content/YOLOX_OBB/tools/yolox/ops/pytorch/nms_rotated/__init__.py)
