### ISSUE TITLE
Import error : No module named 'general'

### ISSUE THREAD

**Issue by tinly00** [DDGRCF/YOLOX_OBB#15]
when i run the train_rotation.py, i got an error:

```jsx
D:\python3.9.7\python.exe E:/DL/yolov5_rotation-master/yolov5_rotation-master/train_rotation.py
Traceback (most recent call last):
  File "E:\DL\yolov5_rotation-master\yolov5_rotation-master\utils\datasets.py", line 29, in <module>
    from general import check_requirements, check_file, check_dataset, xyxy2xywh, xywh2xyxy, xywhn2xyxy, xyn2xy, \
ModuleNotFoundError: No module named 'general'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:\DL\yolov5_rotation-master\yolov5_rotation-master\train_rotation.py", line 25, in <module>
    import test_rotation  as test# import test.py to get mAP after each epoch
  File "E:\DL\yolov5_rotation-master\yolov5_rotation-master\test_rotation.py", line 6, in <module>
    from utils.rotation_nms import caculate_iou_rotation
  File "E:\DL\yolov5_rotation-master\yolov5_rotation-master\utils\__init__.py", line 2, in <module>
    from utils.datasets import LoadStreams, LoadImages
  File "E:\DL\yolov5_rotation-master\yolov5_rotation-master\utils\datasets.py", line 33, in <module>
    from general import check_requirements, check_file, check_dataset, xyxy2xywh, xywh2xyxy, xywhn2xyxy, xyn2xy, \
ModuleNotFoundError: No module named 'general'

Process finished with exit code 
```

The datasets.py 
![1](https://user-images.githubusercontent.com/93133444/162564489-991c6ef6-f5b5-4aa1-97a3-9db5141c8d40.png)

it has red underlines under the utils and it is error with no module named 'general'

i do not know how to solve...

**Comment by tinly00** [comment]
oh!  i got it!
we need to add the upper file-name:
```javascript
from yolov5_rotation-master import xxx
```
and then the error solved.
