### ISSUE TITLE
搭建环境过程中的错误

### ISSUE THREAD

**Issue by Baiyixuan1113** [DDGRCF/YOLOX_OBB#16]
您好，我在使用您的代码搭建环境的时候，遇到了问题，我的电脑环境是这样的
- Ubuntu 18.04
- cuda 10.2
- cudnn 8.0.3
- python 3.7(miniconda)
- torch 1.10.1
- BboxToolkit 1.0
我可以正常完成BboxToolkit的编译，但是在编译yolox时，报错如下:
```
(yolox_obb) etop@etop-dl:/home/Data/Projects/YOLOX_OBB-master$ pip install -v -e .
Using pip 21.2.2 from /home/etop/miniconda3/envs/yolox_obb/lib/python3.7/site-packages/pip (python 3.7)
Obtaining file:///home/Data/Projects/YOLOX_OBB-master
    Running command python setup.py egg_info
    running egg_info
    creating /tmp/pip-pip-egg-info-52_4gdv_/yolox.egg-info
    writing /tmp/pip-pip-egg-info-52_4gdv_/yolox.egg-info/PKG-INFO
    writing dependency_links to /tmp/pip-pip-egg-info-52_4gdv_/yolox.egg-info/dependency_links.txt
    writing top-level names to /tmp/pip-pip-egg-info-52_4gdv_/yolox.egg-info/top_level.txt
    writing manifest file '/tmp/pip-pip-egg-info-52_4gdv_/yolox.egg-info/SOURCES.txt'
    reading manifest file '/tmp/pip-pip-egg-info-52_4gdv_/yolox.egg-info/SOURCES.txt'
    adding license file 'LICENSE'
    writing manifest file '/tmp/pip-pip-egg-info-52_4gdv_/yolox.egg-info/SOURCES.txt'
    /home/etop/miniconda3/envs/yolox_obb/lib/python3.7/distutils/extension.py:131: UserWarning: Unknown Extension options: 'extra_compilr_args'
      warnings.warn(msg)
Installing collected packages: yolox
  Running setup.py develop for yolox
    Running command /home/etop/miniconda3/envs/yolox_obb/bin/python -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/home/Data/Projects/YOLOX_OBB-master/setup.py'"'"'; __file__='"'"'/home/Data/Projects/YOLOX_OBB-master/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' develop --no-deps
    running develop
    running egg_info
    writing yolox.egg-info/PKG-INFO
    writing dependency_links to yolox.egg-info/dependency_links.txt
    writing top-level names to yolox.egg-info/top_level.txt
    reading manifest file 'yolox.egg-info/SOURCES.txt'
    adding license file 'LICENSE'
    writing manifest file 'yolox.egg-info/SOURCES.txt'
    running build_ext
    building 'yolox._C' extension
    Emitting ninja build file /home/Data/Projects/YOLOX_OBB-master/build/temp.linux-x86_64-3.7/build.ninja...
    Compiling objects...
    Allowing ninja to set a default number of workers... (overridable by setting the environment variable MAX_JOBS=N)
    /home/etop/miniconda3/envs/yolox_obb/lib/python3.7/distutils/extension.py:131: UserWarning: Unknown Extension options: 'extra_compilr_args'
      warnings.warn(msg)
    ninja: no work to do.
    g++ -pthread -shared -B /home/etop/miniconda3/envs/yolox_obb/compiler_compat -L/home/etop/miniconda3/envs/yolox_obb/lib -Wl,-rpath=/home/etop/miniconda3/envs/yolox_obb/lib -Wl,--no-as-needed -Wl,--sysroot=/ /home/Data/Projects/YOLOX_OBB-master/build/temp.linux-x86_64-3.7/home/Data/Projects/YOLOX_OBB-master/yolox/layers/csrc/vision.o /home/Data/Projects/YOLOX_OBB-master/build/temp.linux-x86_64-3.7/home/Data/Projects/YOLOX_OBB-master/yolox/layers/csrc/cocoeval/cocoeval.o -L/home/etop/miniconda3/envs/yolox_obb/lib/python3.7/site-packages/torch/lib -lc10 -ltorch -ltorch_cpu -ltorch_python -o build/lib.linux-x86_64-3.7/yolox/_C.cpython-37m-x86_64-linux-gnu.so
    building 'yolox.ops.pytorch.box_iou_rotated.box_iou_rotated_ext' extension
    Emitting ninja build file /home/Data/Projects/YOLOX_OBB-master/build/temp.linux-x86_64-3.7/build.ninja...
    Compiling objects...
    Allowing ninja to set a default number of workers... (overridable by setting the environment variable MAX_JOBS=N)
    ninja: no work to do.
    g++ -pthread -shared -B /home/etop/miniconda3/envs/yolox_obb/compiler_compat -L/home/etop/miniconda3/envs/yolox_obb/lib -Wl,-rpath=/home/etop/miniconda3/envs/yolox_obb/lib -Wl,--no-as-needed -Wl,--sysroot=/ /home/Data/Projects/YOLOX_OBB-master/build/temp.linux-x86_64-3.7/yolox/ops/pytorch/box_iou_rotated/src/box_iou_rotated_cpu.o /home/Data/Projects/YOLOX_OBB-master/build/temp.linux-x86_64-3.7/yolox/ops/pytorch/box_iou_rotated/src/box_iou_rotated_ext.o /home/Data/Projects/YOLOX_OBB-master/build/temp.linux-x86_64-3.7/yolox/ops/pytorch/box_iou_rotated/src/box_iou_rotated_cuda.o -L/home/etop/miniconda3/envs/yolox_obb/lib/python3.7/site-packages/torch/lib -L/usr/local/cuda/lib64 -lc10 -ltorch -ltorch_cpu -ltorch_python -lcudart -lc10_cuda -ltorch_cuda -o build/lib.linux-x86_64-3.7/yolox/ops/pytorch/box_iou_rotated/box_iou_rotated_ext.cpython-37m-x86_64-linux-gnu.so
    building 'yolox.ops.pytorch.convex.convex_ext' extension
    Emitting ninja build file /home/Data/Projects/YOLOX_OBB-master/build/temp.linux-x86_64-3.7/build.ninja...
    Compiling objects...
    Allowing ninja to set a default number of workers... (overridable by setting the environment variable MAX_JOBS=N)
    ninja: no work to do.
    g++ -pthread -shared -B /home/etop/miniconda3/envs/yolox_obb/compiler_compat -L/home/etop/miniconda3/envs/yolox_obb/lib -Wl,-rpath=/home/etop/miniconda3/envs/yolox_obb/lib -Wl,--no-as-needed -Wl,--sysroot=/ /home/Data/Projects/YOLOX_OBB-master/build/temp.linux-x86_64-3.7/yolox/ops/pytorch/convex/src/convex_cpu.o /home/Data/Projects/YOLOX_OBB-master/build/temp.linux-x86_64-3.7/yolox/ops/pytorch/convex/src/convex_ext.o /home/Data/Projects/YOLOX_OBB-master/build/temp.linux-x86_64-3.7/yolox/ops/pytorch/convex/src/convex_cuda.o -L/home/etop/miniconda3/envs/yolox_obb/lib/python3.7/site-packages/torch/lib -L/usr/local/cuda/lib64 -lc10 -ltorch -ltorch_cpu -ltorch_python -lcudart -lc10_cuda -ltorch_cuda -o build/lib.linux-x86_64-3.7/yolox/ops/pytorch/convex/convex_ext.cpython-37m-x86_64-linux-gnu.so
    building 'yolox.ops.pytorch.nms_rotated.nms_rotated_ext' extension
    Emitting ninja build file /home/Data/Projects/YOLOX_OBB-master/build/temp.linux-x86_64-3.7/build.ninja...
    Compiling objects...
    Allowing ninja to set a default number of workers... (overridable by setting the environment variable MAX_JOBS=N)
    ninja: no work to do.
    g++ -pthread -shared -B /home/etop/miniconda3/envs/yolox_obb/compiler_compat -L/home/etop/miniconda3/envs/yolox_obb/lib -Wl,-rpath=/home/etop/miniconda3/envs/yolox_obb/lib -Wl,--no-as-needed -Wl,--sysroot=/ /home/Data/Projects/YOLOX_OBB-master/build/temp.linux-x86_64-3.7/yolox/ops/pytorch/nms_rotated/src/nms_rotated_cpu.o /home/Data/Projects/YOLOX_OBB-master/build/temp.linux-x86_64-3.7/yolox/ops/pytorch/nms_rotated/src/nms_rotated_ext.o /home/Data/Projects/YOLOX_OBB-master/build/temp.linux-x86_64-3.7/yolox/ops/pytorch/nms_rotated/src/nms_rotated_cuda.o /home/Data/Projects/YOLOX_OBB-master/build/temp.linux-x86_64-3.7/yolox/ops/pytorch/nms_rotated/src/poly_nms_cuda.o -L/home/etop/miniconda3/envs/yolox_obb/lib/python3.7/site-packages/torch/lib -L/usr/local/cuda/lib64 -lc10 -ltorch -ltorch_cpu -ltorch_python -lcudart -lc10_cuda -ltorch_cuda -o build/lib.linux-x86_64-3.7/yolox/ops/pytorch/nms_rotated/nms_rotated_ext.cpython-37m-x86_64-linux-gnu.so
    building 'yolox.ops.onnxruntime.ort_ext' extension
    Emitting ninja build file /home/Data/Projects/YOLOX_OBB-master/build/temp.linux-x86_64-3.7/build.ninja...
    Compiling objects...
    Allowing ninja to set a default number of workers... (overridable by setting the environment variable MAX_JOBS=N)
    [1/2] c++ -MMD -MF /home/Data/Projects/YOLOX_OBB-master/build/temp.linux-x86_64-3.7/yolox/ops/onnxruntime/register_onnxruntime/cpu/register_onnxruntime.o.d -pthread -B /home/etop/miniconda3/envs/yolox_obb/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -I/home/Data/Projects/YOLOX_OBB-master/yolox/ops/onnxruntime/register_onnxruntime -I/home/Data/Projects/YOLOX_OBB-master/yolox/ops/onnxruntime/common -I/home/Data/Projects/YOLOX_OBB-master/yolox/ops/onnxruntime/rotated_nms -I/home/Data/Projects/YOLOX_OBB-master/0/include -I/home/etop/miniconda3/envs/yolox_obb/lib/python3.7/site-packages/torch/include -I/home/etop/miniconda3/envs/yolox_obb/lib/python3.7/site-packages/torch/include/torch/csrc/api/include -I/home/etop/miniconda3/envs/yolox_obb/lib/python3.7/site-packages/torch/include/TH -I/home/etop/miniconda3/envs/yolox_obb/lib/python3.7/site-packages/torch/include/THC -I/home/etop/miniconda3/envs/yolox_obb/include/python3.7m -c -c /home/Data/Projects/YOLOX_OBB-master/yolox/ops/onnxruntime/register_onnxruntime/cpu/register_onnxruntime.cpp -o /home/Data/Projects/YOLOX_OBB-master/build/temp.linux-x86_64-3.7/yolox/ops/onnxruntime/register_onnxruntime/cpu/register_onnxruntime.o -O2 -std=c++14 -Wall -DTORCH_API_INCLUDE_EXTENSION_H '-DPYBIND11_COMPILER_TYPE="_gcc"' '-DPYBIND11_STDLIB="_libstdcpp"' '-DPYBIND11_BUILD_ABI="_cxxabi1011"' -DTORCH_EXTENSION_NAME=ort_ext -D_GLIBCXX_USE_CXX11_ABI=0
    FAILED: /home/Data/Projects/YOLOX_OBB-master/build/temp.linux-x86_64-3.7/yolox/ops/onnxruntime/register_onnxruntime/cpu/register_onnxruntime.o
    c++ -MMD -MF /home/Data/Projects/YOLOX_OBB-master/build/temp.linux-x86_64-3.7/yolox/ops/onnxruntime/register_onnxruntime/cpu/register_onnxruntime.o.d -pthread -B /home/etop/miniconda3/envs/yolox_obb/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -I/home/Data/Projects/YOLOX_OBB-master/yolox/ops/onnxruntime/register_onnxruntime -I/home/Data/Projects/YOLOX_OBB-master/yolox/ops/onnxruntime/common -I/home/Data/Projects/YOLOX_OBB-master/yolox/ops/onnxruntime/rotated_nms -I/home/Data/Projects/YOLOX_OBB-master/0/include -I/home/etop/miniconda3/envs/yolox_obb/lib/python3.7/site-packages/torch/include -I/home/etop/miniconda3/envs/yolox_obb/lib/python3.7/site-packages/torch/include/torch/csrc/api/include -I/home/etop/miniconda3/envs/yolox_obb/lib/python3.7/site-packages/torch/include/TH -I/home/etop/miniconda3/envs/yolox_obb/lib/python3.7/site-packages/torch/include/THC -I/home/etop/miniconda3/envs/yolox_obb/include/python3.7m -c -c /home/Data/Projects/YOLOX_OBB-master/yolox/ops/onnxruntime/register_onnxruntime/cpu/register_onnxruntime.cpp -o /home/Data/Projects/YOLOX_OBB-master/build/temp.linux-x86_64-3.7/yolox/ops/onnxruntime/register_onnxruntime/cpu/register_onnxruntime.o -O2 -std=c++14 -Wall -DTORCH_API_INCLUDE_EXTENSION_H '-DPYBIND11_COMPILER_TYPE="_gcc"' '-DPYBIND11_STDLIB="_libstdcpp"' '-DPYBIND11_BUILD_ABI="_cxxabi1011"' -DTORCH_EXTENSION_NAME=ort_ext -D_GLIBCXX_USE_CXX11_ABI=0
    cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++
    In file included from /home/Data/Projects/YOLOX_OBB-master/yolox/ops/onnxruntime/register_onnxruntime/cpu/register_onnxruntime.cpp:1:0:
    /home/Data/Projects/YOLOX_OBB-master/yolox/ops/onnxruntime/register_onnxruntime/register_onnxruntime.h:4:10: fatal error: onnxruntime_c_api.h: 没有那个文件或目录
     #include <onnxruntime_c_api.h>
              ^~~~~~~~~~~~~~~~~~~~~
    compilation terminated.
    [2/2] c++ -MMD -MF /home/Data/Projects/YOLOX_OBB-master/build/temp.linux-x86_64-3.7/yolox/ops/onnxruntime/rotated_nms/cpu/rotated_nms.o.d -pthread -B /home/etop/miniconda3/envs/yolox_obb/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -I/home/Data/Projects/YOLOX_OBB-master/yolox/ops/onnxruntime/register_onnxruntime -I/home/Data/Projects/YOLOX_OBB-master/yolox/ops/onnxruntime/common -I/home/Data/Projects/YOLOX_OBB-master/yolox/ops/onnxruntime/rotated_nms -I/home/Data/Projects/YOLOX_OBB-master/0/include -I/home/etop/miniconda3/envs/yolox_obb/lib/python3.7/site-packages/torch/include -I/home/etop/miniconda3/envs/yolox_obb/lib/python3.7/site-packages/torch/include/torch/csrc/api/include -I/home/etop/miniconda3/envs/yolox_obb/lib/python3.7/site-packages/torch/include/TH -I/home/etop/miniconda3/envs/yolox_obb/lib/python3.7/site-packages/torch/include/THC -I/home/etop/miniconda3/envs/yolox_obb/include/python3.7m -c -c /home/Data/Projects/YOLOX_OBB-master/yolox/ops/onnxruntime/rotated_nms/cpu/rotated_nms.cpp -o /home/Data/Projects/YOLOX_OBB-master/build/temp.linux-x86_64-3.7/yolox/ops/onnxruntime/rotated_nms/cpu/rotated_nms.o -O2 -std=c++14 -Wall -DTORCH_API_INCLUDE_EXTENSION_H '-DPYBIND11_COMPILER_TYPE="_gcc"' '-DPYBIND11_STDLIB="_libstdcpp"' '-DPYBIND11_BUILD_ABI="_cxxabi1011"' -DTORCH_EXTENSION_NAME=ort_ext -D_GLIBCXX_USE_CXX11_ABI=0
    FAILED: /home/Data/Projects/YOLOX_OBB-master/build/temp.linux-x86_64-3.7/yolox/ops/onnxruntime/rotated_nms/cpu/rotated_nms.o
    c++ -MMD -MF /home/Data/Projects/YOLOX_OBB-master/build/temp.linux-x86_64-3.7/yolox/ops/onnxruntime/rotated_nms/cpu/rotated_nms.o.d -pthread -B /home/etop/miniconda3/envs/yolox_obb/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -I/home/Data/Projects/YOLOX_OBB-master/yolox/ops/onnxruntime/register_onnxruntime -I/home/Data/Projects/YOLOX_OBB-master/yolox/ops/onnxruntime/common -I/home/Data/Projects/YOLOX_OBB-master/yolox/ops/onnxruntime/rotated_nms -I/home/Data/Projects/YOLOX_OBB-master/0/include -I/home/etop/miniconda3/envs/yolox_obb/lib/python3.7/site-packages/torch/include -I/home/etop/miniconda3/envs/yolox_obb/lib/python3.7/site-packages/torch/include/torch/csrc/api/include -I/home/etop/miniconda3/envs/yolox_obb/lib/python3.7/site-packages/torch/include/TH -I/home/etop/miniconda3/envs/yolox_obb/lib/python3.7/site-packages/torch/include/THC -I/home/etop/miniconda3/envs/yolox_obb/include/python3.7m -c -c /home/Data/Projects/YOLOX_OBB-master/yolox/ops/onnxruntime/rotated_nms/cpu/rotated_nms.cpp -o /home/Data/Projects/YOLOX_OBB-master/build/temp.linux-x86_64-3.7/yolox/ops/onnxruntime/rotated_nms/cpu/rotated_nms.o -O2 -std=c++14 -Wall -DTORCH_API_INCLUDE_EXTENSION_H '-DPYBIND11_COMPILER_TYPE="_gcc"' '-DPYBIND11_STDLIB="_libstdcpp"' '-DPYBIND11_BUILD_ABI="_cxxabi1011"' -DTORCH_EXTENSION_NAME=ort_ext -D_GLIBCXX_USE_CXX11_ABI=0
    cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++
    In file included from /home/Data/Projects/YOLOX_OBB-master/yolox/ops/onnxruntime/rotated_nms/cpu/rotated_nms.cpp:7:0:
    /home/Data/Projects/YOLOX_OBB-master/yolox/ops/onnxruntime/common/ort_utils.h:3:10: fatal error: onnxruntime_cxx_api.h: 没有那个文件或目录
     #include <onnxruntime_cxx_api.h>
              ^~~~~~~~~~~~~~~~~~~~~~~
    compilation terminated.
    ninja: build stopped: subcommand failed.
    Traceback (most recent call last):
      File "/home/etop/miniconda3/envs/yolox_obb/lib/python3.7/site-packages/torch/utils/cpp_extension.py", line 1723, in _run_ninja_build
        env=env)
      File "/home/etop/miniconda3/envs/yolox_obb/lib/python3.7/subprocess.py", line 512, in run
        output=stdout, stderr=stderr)
    subprocess.CalledProcessError: Command '['ninja', '-v']' returned non-zero exit status 1.

    The above exception was the direct cause of the following exception:

    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/home/Data/Projects/YOLOX_OBB-master/setup.py", line 153, in <module>
        packages=setuptools.find_packages(),
      File "/home/etop/miniconda3/envs/yolox_obb/lib/python3.7/site-packages/setuptools/__init__.py", line 153, in setup
        return distutils.core.setup(**attrs)
      File "/home/etop/miniconda3/envs/yolox_obb/lib/python3.7/distutils/core.py", line 148, in setup
        dist.run_commands()
      File "/home/etop/miniconda3/envs/yolox_obb/lib/python3.7/distutils/dist.py", line 966, in run_commands
        self.run_command(cmd)
      File "/home/etop/miniconda3/envs/yolox_obb/lib/python3.7/distutils/dist.py", line 985, in run_command
        cmd_obj.run()
      File "/home/etop/miniconda3/envs/yolox_obb/lib/python3.7/site-packages/setuptools/command/develop.py", line 34, in run
        self.install_for_development()
      File "/home/etop/miniconda3/envs/yolox_obb/lib/python3.7/site-packages/setuptools/command/develop.py", line 114, in install_for_development
        self.run_command('build_ext')
      File "/home/etop/miniconda3/envs/yolox_obb/lib/python3.7/distutils/cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "/home/etop/miniconda3/envs/yolox_obb/lib/python3.7/distutils/dist.py", line 985, in run_command
        cmd_obj.run()
      File "/home/etop/miniconda3/envs/yolox_obb/lib/python3.7/site-packages/setuptools/command/build_ext.py", line 79, in run
        _build_ext.run(self)
      File "/home/etop/miniconda3/envs/yolox_obb/lib/python3.7/site-packages/Cython/Distutils/old_build_ext.py", line 186, in run
        _build_ext.build_ext.run(self)
      File "/home/etop/miniconda3/envs/yolox_obb/lib/python3.7/distutils/command/build_ext.py", line 340, in run
        self.build_extensions()
      File "/home/etop/miniconda3/envs/yolox_obb/lib/python3.7/site-packages/torch/utils/cpp_extension.py", line 735, in build_extensions
        build_ext.build_extensions(self)
      File "/home/etop/miniconda3/envs/yolox_obb/lib/python3.7/site-packages/Cython/Distutils/old_build_ext.py", line 195, in build_extensions
        _build_ext.build_ext.build_extensions(self)
      File "/home/etop/miniconda3/envs/yolox_obb/lib/python3.7/distutils/command/build_ext.py", line 449, in build_extensions
        self._build_extensions_serial()
      File "/home/etop/miniconda3/envs/yolox_obb/lib/python3.7/distutils/command/build_ext.py", line 474, in _build_extensions_serial
        self.build_extension(ext)
      File "/home/etop/miniconda3/envs/yolox_obb/lib/python3.7/site-packages/setuptools/command/build_ext.py", line 202, in build_extension
        _build_ext.build_extension(self, ext)
      File "/home/etop/miniconda3/envs/yolox_obb/lib/python3.7/distutils/command/build_ext.py", line 534, in build_extension
        depends=ext.depends)
      File "/home/etop/miniconda3/envs/yolox_obb/lib/python3.7/site-packages/torch/utils/cpp_extension.py", line 565, in unix_wrap_ninja_compile
        with_cuda=with_cuda)
      File "/home/etop/miniconda3/envs/yolox_obb/lib/python3.7/site-packages/torch/utils/cpp_extension.py", line 1404, in _write_ninja_file_and_compile_objects
        error_prefix='Error compiling objects for extension')
      File "/home/etop/miniconda3/envs/yolox_obb/lib/python3.7/site-packages/torch/utils/cpp_extension.py", line 1733, in _run_ninja_build
        raise RuntimeError(message) from e
    RuntimeError: Error compiling objects for extension
ERROR: Command errored out with exit status 1: /home/etop/miniconda3/envs/yolox_obb/bin/python -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/home/Data/Projects/YOLOX_OBB-master/setup.py'"'"'; __file__='"'"'/home/Data/Projects/YOLOX_OBB-master/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' develop --no-deps Check the logs for full command output.

```
看起来好像是缺少文件，希望您能帮助我。

**Comment by DDGRCF** [comment]
您好，非常抱歉。onnx部分我还没有完成，但是去掉onnx部分编译对整体不影响，你可以在setup中将其杠掉

**Comment by Baiyixuan1113** [comment]
> 您好，非常抱歉。onnx部分我还没有完成，但是去掉onnx部分编译对整体不影响，你可以在setup中将其杠掉

好的，了解了，感谢答复。

**Comment by DDGRCF** [comment]
> > 您好，非常抱歉。onnx部分我还没有完成，但是去掉onnx部分编译对整体不影响，你可以在setup中将其杠掉
> 
> 不好意思，再打扰一下，您的这套代码支持COCO格式数据集训练吗？

你把coco格式转成dota格式，然后再使用BboxToolkit将格式转换为可以训练的格式就行了

**Comment by Baiyixuan1113** [comment]
> > > 您好，非常抱歉。onnx部分我还没有完成，但是去掉onnx部分编译对整体不影响，你可以在setup中将其杠掉
> > 
> > 
> > 不好意思，再打扰一下，您的这套代码支持COCO格式数据集训练吗？
> 
> 你把coco格式转成dota格式，然后再使用BboxToolkit将格式转换为可以训练的格式就行了

是的，我按照您所说的步骤完成了数据集的转换，但我开始训练后，它卡在了初始化阶段，辛苦问您一下可能是什么原因？
终端信息如下：
```
(yolox_obb) etop@etop-dl:/home/Data/Projects/YOLOX_OBB$ python tools/train.py -expn yoloxs_seal_20220411 -f exps/example/yolox_obb/yolox_obb_dota_seal.py -d 1 -b 8
2022-04-11 19:29:43 | INFO     | yolox.core.trainer:132 - args: Namespace(batch_size=8, cache=False, ckpt=None, devices=1, dist_backend='nccl', dist_url=None, exp_file='exps/example/yolox_obb/yolox_obb_dota_seal.py', experiment_name='yoloxs_seal_20220411', fp16=False, machine_rank=0, name=None, num_machines=1, occupy=False, options=None, resume=False, start_epoch=None)
2022-04-11 19:29:43 | INFO     | yolox.core.trainer:133 - exp value:
╒═══════════════════╤══════════════════════════════════════════════════════╕
│ keys              │ values                                               │
╞═══════════════════╪══════════════════════════════════════════════════════╡
│ seed              │ None                                                 │
├───────────────────┼──────────────────────────────────────────────────────┤
│ output_dir        │ 'YOLOX_outputs'                                      │
├───────────────────┼──────────────────────────────────────────────────────┤
│ print_interval    │ 10                                                   │
├───────────────────┼──────────────────────────────────────────────────────┤
│ eval_interval     │ 10                                                   │
├───────────────────┼──────────────────────────────────────────────────────┤
│ modules_config    │ 'configs/modules/yoloxs_obb.yaml'                    │
├───────────────────┼──────────────────────────────────────────────────────┤
│ losses_config     │ 'configs/losses/yolox_losses_obb.yaml'               │
├───────────────────┼──────────────────────────────────────────────────────┤
│ dataset_config    │ 'configs/datasets/dota_seal.yaml'                    │
├───────────────────┼──────────────────────────────────────────────────────┤
│ data_num_workers  │ 12                                                   │
├───────────────────┼──────────────────────────────────────────────────────┤
│ input_size        │ (640, 640)                                           │
├───────────────────┼──────────────────────────────────────────────────────┤
│ multiscale_range  │ 5                                                    │
├───────────────────┼──────────────────────────────────────────────────────┤
│ mosaic_prob       │ 1.0                                                  │
├───────────────────┼──────────────────────────────────────────────────────┤
│ mixup_prob        │ 1.0                                                  │
├───────────────────┼──────────────────────────────────────────────────────┤
│ hsv_prob          │ 1.0                                                  │
├───────────────────┼──────────────────────────────────────────────────────┤
│ flip_prob         │ 0.5                                                  │
├───────────────────┼──────────────────────────────────────────────────────┤
│ degrees           │ 10.0                                                 │
├───────────────────┼──────────────────────────────────────────────────────┤
│ translate         │ 0.1                                                  │
├───────────────────┼──────────────────────────────────────────────────────┤
│ mosaic_scale      │ (0.4, 1.2)                                           │
├───────────────────┼──────────────────────────────────────────────────────┤
│ mixup_scale       │ (0.4, 1.2)                                           │
├───────────────────┼──────────────────────────────────────────────────────┤
│ shear             │ 2                                                    │
├───────────────────┼──────────────────────────────────────────────────────┤
│ perspective       │ 0.0                                                  │
├───────────────────┼──────────────────────────────────────────────────────┤
│ enable_mixup      │ True                                                 │
├───────────────────┼──────────────────────────────────────────────────────┤
│ warmup_epochs     │ 1                                                    │
├───────────────────┼──────────────────────────────────────────────────────┤
│ max_epoch         │ 100                                                  │
├───────────────────┼──────────────────────────────────────────────────────┤
│ warmup_lr         │ 0                                                    │
├───────────────────┼──────────────────────────────────────────────────────┤
│ basic_lr_per_img  │ 0.00015625                                           │
├───────────────────┼──────────────────────────────────────────────────────┤
│ scheduler         │ 'yoloxwarmcos'                                       │
├───────────────────┼──────────────────────────────────────────────────────┤
│ no_aug_epochs     │ 15                                                   │
├───────────────────┼──────────────────────────────────────────────────────┤
│ min_lr_ratio      │ 0.05                                                 │
├───────────────────┼──────────────────────────────────────────────────────┤
│ ema               │ True                                                 │
├───────────────────┼──────────────────────────────────────────────────────┤
│ no_eval           │ False                                                │
├───────────────────┼──────────────────────────────────────────────────────┤
│ weight_decay      │ 0.0005                                               │
├───────────────────┼──────────────────────────────────────────────────────┤
│ momentum          │ 0.9                                                  │
├───────────────────┼──────────────────────────────────────────────────────┤
│ exp_name          │ 'yoloxs_seal_20220411'                               │
├───────────────────┼──────────────────────────────────────────────────────┤
│ test_size         │ (640, 640)                                           │
├───────────────────┼──────────────────────────────────────────────────────┤
│ postprocess_cfg   │ {'conf_thre': 0.01, 'nms_thre': 0.65}                │
├───────────────────┼──────────────────────────────────────────────────────┤
│ data_dir          │ 'datasets/DOTA1_0'                                   │
├───────────────────┼──────────────────────────────────────────────────────┤
│ train_ann         │ 'trainval'                                           │
├───────────────────┼──────────────────────────────────────────────────────┤
│ val_ann           │ 'val'                                                │
├───────────────────┼──────────────────────────────────────────────────────┤
│ num_classes       │ 4                                                    │
├───────────────────┼──────────────────────────────────────────────────────┤
│ copy_paste_prob   │ 1.0                                                  │
├───────────────────┼──────────────────────────────────────────────────────┤
│ enable_copy_paste │ True                                                 │
├───────────────────┼──────────────────────────────────────────────────────┤
│ enable_debug      │ False                                                │
├───────────────────┼──────────────────────────────────────────────────────┤
│ enable_resample   │ True                                                 │
├───────────────────┼──────────────────────────────────────────────────────┤
│ aug_ignore        │ None                                                 │
├───────────────────┼──────────────────────────────────────────────────────┤
│ empty_ignore      │ True                                                 │
├───────────────────┼──────────────────────────────────────────────────────┤
│ evaluate_cfg      │ {'is_merge': False, 'is_submiss': False, 'nproc': 1} │
├───────────────────┼──────────────────────────────────────────────────────┤
│ test_ann          │ 'test'                                               │
╘═══════════════════╧══════════════════════════════════════════════════════╛
2022-04-11 19:29:43 | INFO     | yolox.models.parse_model:17 - overriding modules.yaml num_classes=80 with num_classes=4
/home/etop/miniconda3/envs/yolox_obb/lib/python3.7/site-packages/torch/functional.py:445: UserWarning: torch.meshgrid: in an upcoming release, it will be required to pass the indexing argument. (Triggered internally at  ../aten/src/ATen/native/TensorShape.cpp:2157.)
  return _VF.meshgrid(tensors, **kwargs)  # type: ignore[attr-defined]
2022-04-11 19:29:43 | INFO     | yolox.core.trainer:139 - Model Summary: Params: 8.05M, Gflops: 21.68
2022-04-11 19:29:47 | INFO     | yolox.core.trainer:157 - init prefetcher, this might take one minute or less...
```

**Comment by DDGRCF** [comment]
> 
请问卡了多久，是一直卡吗。。。

**Comment by Baiyixuan1113** [comment]
> > 
> 
> 请问卡了多久，是一直卡吗。。。

是的，它停留在这了一整晚。
