### ISSUE TITLE
train.py 文件运行circular import

### ISSUE THREAD

**Issue by tinly00** [DDGRCF/YOLOX_OBB#21]
Hello！
我在运行train.py时出现报错：
```javascript
C:\Users\Administrator\anaconda3\envs\yolov5_py39cu102\python.exe E:/DL/yolov5_obb_master/yolov5_obb_master/train.py
Traceback (most recent call last):
  File "E:\DL\yolov5_obb_master\yolov5_obb_master\train.py", line 34, in <module>
    import val  # for end-of-epoch mAP
  File "E:\DL\yolov5_obb_master\yolov5_obb_master\val.py", line 28, in <module>
    from models.common import DetectMultiBackend
  File "E:\DL\yolov5_obb_master\yolov5_obb_master\models\common.py", line 23, in <module>
    from utils.datasets import exif_transpose, letterbox
  File "E:\DL\yolov5_obb_master\yolov5_obb_master\utils\datasets.py", line 28, in <module>
    from utils.augmentations import Albumentations, augment_hsv, copy_paste, letterbox, mixup, random_perspective
  File "E:\DL\yolov5_obb_master\yolov5_obb_master\utils\augmentations.py", line 12, in <module>
    from utils.general import LOGGER, check_version, colorstr, resample_segments, segment2box
  File "E:\DL\yolov5_obb_master\yolov5_obb_master\utils\general.py", line 35, in <module>
    from yolov5_obb_master.utils.nms_rotated import obb_nms
  File "E:\DL\yolov5_obb_master\yolov5_obb_master\utils\nms_rotated\__init__.py", line 1, in <module>
    from .nms_rotated_wrapper import obb_nms, poly_nms
  File "E:\DL\yolov5_obb_master\yolov5_obb_master\utils\nms_rotated\nms_rotated_wrapper.py", line 4, in <module>
    from . import nms_rotated_ext
ImportError: cannot import name 'nms_rotated_ext' from partially initialized module 'yolov5_obb_master.utils.nms_rotated' (most likely due to a circular import) (E:\DL\yolov5_obb_master\yolov5_obb_master\utils\nms_rotated\__init__.py)

Process finished with exit code 1
```
点击进入报错的nms_rotated_ext.py文件进行查看：
![1649941940(1)](https://user-images.githubusercontent.com/93133444/163397927-92d03e74-50c2-4075-951f-85acbce39c8c.png)
查看import 的nms_rotated_ext发现它是utils中src文件夹下的.cpp文件：
![1649942128(1)](https://user-images.githubusercontent.com/93133444/163398492-a7fbda05-ebda-4dcd-998f-6f67cfc8ad8c.png)
请问是需要添加调用.cpp文件模块吗？还是要如何解决这个问题？
@DDGRCF  
谢谢！

**Comment by lalalagogogochong** [comment]
> Hello！ 我在运行train.py时出现报错：
> 
> ```js
> C:\Users\Administrator\anaconda3\envs\yolov5_py39cu102\python.exe E:/DL/yolov5_obb_master/yolov5_obb_master/train.py
> Traceback (most recent call last):
>   File "E:\DL\yolov5_obb_master\yolov5_obb_master\train.py", line 34, in <module>
>     import val  # for end-of-epoch mAP
>   File "E:\DL\yolov5_obb_master\yolov5_obb_master\val.py", line 28, in <module>
>     from models.common import DetectMultiBackend
>   File "E:\DL\yolov5_obb_master\yolov5_obb_master\models\common.py", line 23, in <module>
>     from utils.datasets import exif_transpose, letterbox
>   File "E:\DL\yolov5_obb_master\yolov5_obb_master\utils\datasets.py", line 28, in <module>
>     from utils.augmentations import Albumentations, augment_hsv, copy_paste, letterbox, mixup, random_perspective
>   File "E:\DL\yolov5_obb_master\yolov5_obb_master\utils\augmentations.py", line 12, in <module>
>     from utils.general import LOGGER, check_version, colorstr, resample_segments, segment2box
>   File "E:\DL\yolov5_obb_master\yolov5_obb_master\utils\general.py", line 35, in <module>
>     from yolov5_obb_master.utils.nms_rotated import obb_nms
>   File "E:\DL\yolov5_obb_master\yolov5_obb_master\utils\nms_rotated\__init__.py", line 1, in <module>
>     from .nms_rotated_wrapper import obb_nms, poly_nms
>   File "E:\DL\yolov5_obb_master\yolov5_obb_master\utils\nms_rotated\nms_rotated_wrapper.py", line 4, in <module>
>     from . import nms_rotated_ext
> ImportError: cannot import name 'nms_rotated_ext' from partially initialized module 'yolov5_obb_master.utils.nms_rotated' (most likely due to a circular import) (E:\DL\yolov5_obb_master\yolov5_obb_master\utils\nms_rotated\__init__.py)
> 
> Process finished with exit code 1
> ```
> 
> 点击进入报错的nms_rotated_ext.py文件进行查看： ![1649941940(1)](https://user-images.githubusercontent.com/93133444/163397927-92d03e74-50c2-4075-951f-85acbce39c8c.png) 查看import 的nms_rotated_ext发现它是utils中src文件夹下的.cpp文件： ![1649942128(1)](https://user-images.githubusercontent.com/93133444/163398492-a7fbda05-ebda-4dcd-998f-6f67cfc8ad8c.png) 请问是需要添加调用.cpp文件模块吗？还是要如何解决这个问题？ @DDGRCF 谢谢！

得编译环境，https://github.com/DDGRCF/YOLOX_OBB/blob/master/docs/quick_run.md

**Comment by tinly00** [comment]
> > Hello！ 我在运行train.py时出现报错：
> > ```js
> > C:\Users\Administrator\anaconda3\envs\yolov5_py39cu102\python.exe E:/DL/yolov5_obb_master/yolov5_obb_master/train.py
> > Traceback (most recent call last):
> >   File "E:\DL\yolov5_obb_master\yolov5_obb_master\train.py", line 34, in <module>
> >     import val  # for end-of-epoch mAP
> >   File "E:\DL\yolov5_obb_master\yolov5_obb_master\val.py", line 28, in <module>
> >     from models.common import DetectMultiBackend
> >   File "E:\DL\yolov5_obb_master\yolov5_obb_master\models\common.py", line 23, in <module>
> >     from utils.datasets import exif_transpose, letterbox
> >   File "E:\DL\yolov5_obb_master\yolov5_obb_master\utils\datasets.py", line 28, in <module>
> >     from utils.augmentations import Albumentations, augment_hsv, copy_paste, letterbox, mixup, random_perspective
> >   File "E:\DL\yolov5_obb_master\yolov5_obb_master\utils\augmentations.py", line 12, in <module>
> >     from utils.general import LOGGER, check_version, colorstr, resample_segments, segment2box
> >   File "E:\DL\yolov5_obb_master\yolov5_obb_master\utils\general.py", line 35, in <module>
> >     from yolov5_obb_master.utils.nms_rotated import obb_nms
> >   File "E:\DL\yolov5_obb_master\yolov5_obb_master\utils\nms_rotated\__init__.py", line 1, in <module>
> >     from .nms_rotated_wrapper import obb_nms, poly_nms
> >   File "E:\DL\yolov5_obb_master\yolov5_obb_master\utils\nms_rotated\nms_rotated_wrapper.py", line 4, in <module>
> >     from . import nms_rotated_ext
> > ImportError: cannot import name 'nms_rotated_ext' from partially initialized module 'yolov5_obb_master.utils.nms_rotated' (most likely due to a circular import) (E:\DL\yolov5_obb_master\yolov5_obb_master\utils\nms_rotated\__init__.py)
> > 
> > Process finished with exit code 1
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 点击进入报错的nms_rotated_ext.py文件进行查看： ![1649941940(1)](https://user-images.githubusercontent.com/93133444/163397927-92d03e74-50c2-4075-951f-85acbce39c8c.png) 查看import 的nms_rotated_ext发现它是utils中src文件夹下的.cpp文件： ![1649942128(1)](https://user-images.githubusercontent.com/93133444/163398492-a7fbda05-ebda-4dcd-998f-6f67cfc8ad8c.png) 请问是需要添加调用.cpp文件模块吗？还是要如何解决这个问题？ @DDGRCF 谢谢！
> 
> 得编译环境，https://github.com/DDGRCF/YOLOX_OBB/blob/master/docs/quick_run.md

hello! 谢谢！我还想问一下，我这个是windows跑的，windows也是一样跑吗？
